api: 
  build: ./api
  ports: 
    - 3000:3000
  volumes: 
    - ./api:/go/src/github.com/stevengeorgeharris/nowaste/api
  environment: 
    - ENV_PORT=:3000
    - TEST_MESSAGE=Hello from Steven
  links:
    - db

db: 
  build: ./db
  ports:
  - "3010:3010"
  environment:
    MONGODB_USER: "steven"
    MONGODB_DATABASE: "admin"
    MONGODB_PASS: "admin"

seed-db: 
  build: ./db-seed
  links:
    - db

